
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hvuboibvovlazhxfjtnl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh2dWJvaWJ2b3ZsYXpoeGZqdG5sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzNjEwMTgsImV4cCI6MjA1OTkzNzAxOH0.TY_OA5vZg7yArxEbqguAN79NI8dP_fxuiZHrbcVDO90";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
